// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadDptWeatherData(arg1) {
  return window['go']['main']['App']['DownloadDptWeatherData'](arg1);
}

export function GetLoadedSource() {
  return window['go']['main']['App']['GetLoadedSource']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}
