// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function DownloadDptWeatherData(arg1:string):Promise<void>;

export function GetAvgRainAllStations():Promise<Array<data.StationAvgRain>>;

export function GetLoadedSource():Promise<Array<data.LoadedDpt>>;

export function GetStationRain(arg1:string):Promise<Array<data.RainByStation>>;

export function GetStationRainData(arg1:string):Promise<Array<data.WeatherData>>;

export function GetStations():Promise<Array<data.StationInfo>>;

export function GetUsername():Promise<string>;
