// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function DownloadDptWeatherData(arg1:string):Promise<void>;

export function GetLoadedSource():Promise<Array<data.LoadedDpt>>;

export function GetStations():Promise<Array<data.StationInfo>>;

export function GetUsername():Promise<string>;
